name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    name: npm-publish-web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Publish if version has been updated
        run: |
          npm install
          npm run publish:web
         # npm publish dist/bfast
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
