name: npm-publish-stable
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    name: npm-publish-stable
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017
      - name: Publish if version has been updated
        run: |
          npm install -g ipfs
          jsipfs init
          jsipfs config --json Addresses.API '["/ip4/127.0.0.1/tcp/5001"]'
          jsipfs daemon &
          npm install -g yarn
          yarn install
          yarn test
          yarn build
          npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
